version: '3'

services:
  geth:
    build: .
    ports:
      - "8551:8551"
      - "8545:8545"
    command:
      - ./geth-entrypoint.sh
  prysm:
    build: .
    ports:
      - "3500:3500"
      - "4000:4000"
      - "12000:12000"
      - "13000:13000"
    depends_on:
      - geth
    command:
      - ./prysm-entrypoint.sh
