version: '3.4'

services:
  geth:
    build: .
    ports:
      - "8551:8551"
      - "8545:8545"
      - "30303:30303"
    entrypoint: ['/usr/bin/geth-entrypoint.sh']
    volumes:
      - ./genesis.json:/etc/genesis.json:ro
      - ./geth-entrypoint.sh:/usr/bin/geth-entrypoint.sh
      - ./geth_static_nodes.toml:/etc/geth.toml
      - ./jwtsecret:/etc/jwtsecret:ro

  prysm:
    build: .
    ports:
      - "3500:3500"
      - "4000:4000"
      - "12000:12000"
      - "13000:13000"
    environment:
      - EXECUTION_ENDPOINT=http://geth:8551
    depends_on:
      - geth
    command:
      - ./prysm-entrypoint.sh
    volumes:
      - ./genesis.ssz:/etc/genesis.ssz:ro
      - ./config.yml:/etc/config.yml:ro
      - ./jwtsecret:/etc/jwtsecret:ro
